# fly.toml app configuration file generated for scenario on 2025-08-02T22:48:22+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'scenario'
primary_region = 'otp'

[build]
  dockerfile = 'Dockerfile'

  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.3'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
